### ISSUE TITLE
Remove dependency to OpenPDF in pom.xml

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenRTF#3]
Remove dependency to OpenPDF in pom.xml. 

Copy the files from OpenPDF, so that OpenRTF can be used without OpenPDF.  For example com.lowagie.text.DocWriter and the files it refers to, needs to be copied to OpenRTF.

**Comment by Corlobin** [comment]
Hi, I would like to contribute to the project!
Just a question, am I needed to recreate all the code from scratch due to this README clause? 

"In particular, pull requests to the OpenRTF project must only contain code that you have written yourself"

**Comment by andreasrosdal** [comment]
It's great that you want to contribute. Welcome!

You can submit code with the same license, or code which you have written yourself. This README-text is there to prevent people copying code from projects with an incompatible license.

**Comment by osobolev** [comment]
I'd like to know the goal of this issue. Is it to remove unnecessary PDF-specific code for users of OpenRTF?

AFAIK there is quite a lot of shared code between OpenPDF and OpenRTF, the whole com.lowagie.text.* package is used in both libraries. So copying it would create quite large code duplication.

Maybe it's better to create a separate library with shared code?

**Comment by andreasrosdal** [comment]
> Maybe it's better to create a separate library with shared code?

This is a good idea.
